import Diseases from "./css/images/diseases.jpg";

const diseasesInfo = [
    {title: "Heart Disease", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."},
    {title: "Respiratory Disease", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."},
    {title: "Kidney Disease", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."},
    {title: "Influenza (Flu)", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."},
    {title: "Diabetes", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."},
    {title: "Cancer", image: Diseases, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta non tellus vel commodo. Donec gravida lorem a maximus auctor. Curabitur tincidunt magna sit amet cursus fermentum. Ut ut tellus pellentesque, dapibus ipsum placerat, lacinia leo. Aenean vulputate augue nec lectus sodales maximus. Nam et neque mi. Quisque convallis, diam id dictum dictum, justo felis vulputate mauris, id rhoncus lectus neque ac dui. Vestibulum tincidunt risus tincidunt pulvinar rutrum. Suspendisse tortor odio, consequat vitae sodales vel, varius vitae lorem. Etiam mattis orci ac leo volutpat dapibus. Morbi eleifend lectus ipsum, at maximus quam iaculis ut."}
];

export default diseasesInfo;