import All from "./css/images/muscle-body-front/muscle-front.png";
import Head from "./css/images/muscle-body-front/muscle-head.png"; import partHead from "./css/images/muscle-body-front/part-head.png";
import Shoulders from "./css/images/muscle-body-front/muscle-shoulders.png"; import partShoulders from "./css/images/muscle-body-front/part-shoulders.png";
import UpperArm from "./css/images/muscle-body-front/muscle-upper-arm.png"; import partUpperArm from "./css/images/muscle-body-front/part-upper-arm.png";
import Forearm from "./css/images/muscle-body-front/muscle-forearm.png"; import partForearm from "./css/images/muscle-body-front/part-forearm.png";
import Hands from "./css/images/muscle-body-front/muscle-hands.png"; import partHands from "./css/images/muscle-body-front/part-hands.png";
import Chest from "./css/images/muscle-body-front/muscle-chest.png"; import partChest from "./css/images/muscle-body-front/part-chest.png";
import Abdomen from "./css/images/muscle-body-front/muscle-abdomen.png"; import partAbdomen from "./css/images/muscle-body-front/part-abdomen.png";
import Obliques from "./css/images/muscle-body-front/muscle-obliques.png"; import partObliques from "./css/images/muscle-body-front/part-obliques.png";
import Thigh from "./css/images/muscle-body-front/muscle-thigh.png"; import partThigh from "./css/images/muscle-body-front/part-thigh.png";
import LowerLeg from "./css/images/muscle-body-front/muscle-lower-leg.png"; import partLowerLeg from "./css/images/muscle-body-front/part-lower-leg.png";
import Feet from "./css/images/muscle-body-front/muscle-feet.png"; import partFeet from "./css/images/muscle-body-front/part-feet.png";

const musclesFrontInfo = new Map();

musclesFrontInfo.set("All", [All, null, "Muscles are specialized tissues located throughout the body, and they are responsible for both voluntary and involuntary movement.\n\nVoluntary movements are actively facilitated by the person (thought becomes action). Examples include walking, lifting, speaking, and chewing.\n\nInvoluntary movements occur automatically without thought. Examples include breathing, beating of the heart, digestion, and muscle spasms.\n\nMuscles are composed of muscle fibers, which consist of even smaller fibers called myofibrils. Repeating units of sarcomeres comprise each myofibril and include contractile proteins called actin (thin filaments) and myosin (thick filaments). These proteins interact and generate contractile force, sliding the proteins toward each other and resulting in muscle movement.\n\nThere are 3 types of muscles: skeletal, smooth, and cardiac. Skeletal muscles anchor to bones via ligaments and enable voluntary movement. Smooth muscles line the walls of internal organs and blood vessels and enable involuntary movement. Cardiac muscles line the walls of the heart and enable the heart to pump and circulate blood throughout the body."]);
musclesFrontInfo.set("Head", [Head, partHead, "The head is composed of several facial muscles that enable making facial expressions and chewing (mastication). Actions such as smiling, raising of the eyebrows, blinking, and talking are all accomplished by facial muscles.\n\nFun fact: The masseter muscle (responsible for chewing) located in the jaw is the strongest muscle (pound-for-pound) in the body, capable of exerting a bite force of 200 pounds on the molars."]);
musclesFrontInfo.set("Shoulders", [Shoulders, partShoulders, "The shoulder includes the deltoid muscles (informally known as delts), which consist of 3 heads: anterior (front), lateral (middle), and posterior (rear). All 3 heads work together to enable arm movement.\n\nEach head specializes and exerts more force depending on the movement: the anterior head raises the arm forward, the lateral head raises the arm to the side, and the posterior head raises the arm backward.\n\nDue to the shoulder's importance in arm movement and mobility, it is vital to condition the deltoid muscles. Strength exercises that simulate a particular head's movement maximizes that head's muscle engagement (muscle isolation) but significantly reduces the engagement of the other heads.\n\nA popular exercise that effectively targets all 3 heads simultaneously is the shoulder press. Note that the more muscles involved in a movement, the less engaged a particular muscle is compared to a muscle isolation exercise (same idea as lifting a heavy object as a team vs lifting a heavy object by yourself)."]);
musclesFrontInfo.set("Upper Arm", [UpperArm, partUpperArm, "The upper arm anchors the bicep, a powerful muscle that consists of a short and long head. Both heads enable elbow flexion (bending) and forearm supination (outward rotation).\n\nAn effective strength exercise that targets the bicep is bicep curls, a weighted movement that involves bringing the hand to the shoulder (elbow flexion)."]);
musclesFrontInfo.set("Forearm", [Forearm, partForearm, "The forearm muscles include several flexors (bend), extensors (extend), pronators (inward rotation), and supinators (outward rotation). The flexors and extensors bend and extend the wrist and fingers, while the pronators and supinators rotate the hand.\n\nThese muscles are also involved in grip strength - grip exercises like the dead hang and wrist curls engage and strengthen the forearm."]);
musclesFrontInfo.set("Hands", [Hands, partHands, "The hand contains several muscles (intrinsic) that enable the flexion (bend) and extension (extend) of the palm and fingers. While muscles in the forearm (extrinsic) also play a role in these functionalities, the hand muscles are responsible for the more precise movements (enables dexterity)."]);
musclesFrontInfo.set("Chest", [Chest, partChest, "The chest includes the pectoralis major, a large, fan-shaped muscle that consists of 2 main heads: clavicular (upper) and sternocostal (lower).\n\nThe clavicular head originates from the clavicle, while the sternocostal head originates from the sternum. Both heads span across the chest and attach to a nodule located in the upper region of the humerus.\n\nThe pectoralis major is responsible for the adduction (movement toward the midline) and internal rotation of the arm at the shoulder joint. Examples include pushing (forward, up, and down) and bringing the arm across the chest.\n\nExercises that strengthen the chest include the bench press, dips, cable crossovers, and push-ups."]);
musclesFrontInfo.set("Abdomen", [Abdomen, partAbdomen, "The abdominal muscles (also known as the core) are strong bands of muscles that line the trunk of the body.\n\nThe abs maintain trunk stability, enable movement between the ribs and the pelvis (ex: sitting up and bending), and holding internal organs in place. The abs also dynamically adjust their pressure (via contraction and relaxation) to regulate bodily functions such as breathing, coughing, and defecation.\n\nWell-known exercises like the sit-up and crunches target the abdominal muscles, though it is advised to engage in the latter exercise, as sit-ups place unnecessary pressure on the lower spine."]);
musclesFrontInfo.set("Obliques", [Obliques, partObliques, "The obliques are part of the abdominal muscles and consist of the internal and external obliques. With the external obliques layered on top of the internal obliques, both muscles span the sides of the trunk.\n\nThe obliques enable movement between the ribs and the pelvis, specifically allowing the trunk to twist and turn.\n\nAbdominal exercises that incorporate side flexion and trunk rotation like side crunches and bicycle crunches effectively engage the obliques."]);
musclesFrontInfo.set("Thigh", [Thigh, partThigh, "The thigh anchors some of the largest muscles in the body, including the quadriceps (or quads), a muscle that spans from the pelvis to the knee along the front thigh.\n\nThe quads are responsible for hip flexion (moving leg forward at hip joint) and knee extension (straightening of the leg) and stabilization - these functionalities allow the body to perform essential movements such as walking, running, and jumping. They are also the primary muscle group that absorbs impact when the feet hit the ground, which is why it is important to bend the knees upon making contact with the ground.\n\nWalking and running are cardio-based exercises that strengthen the quads in addition to improving endurance and heart health. Another option is the squat, a strength-based compound exercise that works several muscle groups, including the quads."]);
musclesFrontInfo.set("Lower Leg", [LowerLeg, partLowerLeg, "The lower leg includes anterior muscles that stretch along the front of the shin. These muscles are responsible for dorsiflexing (upward movement) the foot and toes, maintaining balance, and stabilizing the ankle and foot.\n\nDorsiflexion of the foot with a resistance band can build anterior muscle strength."]);
musclesFrontInfo.set("Feet", [Feet, partFeet, "The foot contains several muscles (intrinsic) that enable the flexion (bend) and extension (extend) of the toes and stabilization of the arch. While muscles in the lower leg (extrinsic) also play a role in these functionalities, the foot muscles are responsible for the more precise movements."]);

export default musclesFrontInfo;