import All from "./css/images/muscle-body-back/muscle-back.png";
import Traps from "./css/images/muscle-body-back/muscle-traps.png"; import partTraps from "./css/images/muscle-body-back/part-traps.png";
import Shoulders from "./css/images/muscle-body-back/muscle-shoulders.png"; import partShoulders from "./css/images/muscle-body-back/part-shoulders.png";
import UpperArm from "./css/images/muscle-body-back/muscle-upper-arm.png"; import partUpperArm from "./css/images/muscle-body-back/part-upper-arm.png";
import Lats from "./css/images/muscle-body-back/muscle-lats.png"; import partLats from "./css/images/muscle-body-back/part-lats.png";
import LowerBack from "./css/images/muscle-body-back/muscle-lower-back.png"; import partLowerBack from "./css/images/muscle-body-back/part-lower-back.png";
import Glutes from "./css/images/muscle-body-back/muscle-glutes.png"; import partGlutes from "./css/images/muscle-body-back/part-glutes.png";
import Thigh from "./css/images/muscle-body-back/muscle-thigh.png"; import partThigh from "./css/images/muscle-body-back/part-thigh.png";
import LowerLeg from "./css/images/muscle-body-back/muscle-lower-leg.png"; import partLowerLeg from "./css/images/muscle-body-back/part-lower-leg.png";

const musclesBackInfo = new Map();

musclesBackInfo.set("All", [All, null, "Muscles are specialized tissues located throughout the body, and they are responsible for both voluntary and involuntary movement.\n\nVoluntary movements are actively facilitated by the person (thought becomes action). Examples include walking, lifting, speaking, and chewing.\n\nInvoluntary movements occur automatically without thought. Examples include breathing, beating of the heart, digestion, and muscle spasms.\n\nMuscles are composed of muscle fibers, which consist of even smaller fibers called myofibrils. Repeating units of sarcomeres comprise each myofibril and include contractile proteins called actin (thin filaments) and myosin (thick filaments). These proteins interact and generate contractile force, sliding the proteins toward each other and resulting in muscle movement.\n\nThere are 3 types of muscles: skeletal, smooth, and cardiac. Skeletal muscles anchor to bones via ligaments and enable voluntary movement. Smooth muscles line the walls of internal organs and blood vessels and enable involuntary movement. Cardiac muscles line the walls of the heart and enable the heart to pump and circulate blood throughout the body."]);
musclesBackInfo.set("Traps", [Traps, partTraps, "The trapezius muscle (commonly known as the traps) is a large, trapezoidal (diamond-shaped) muscle that spans the neck, collarbone, and the upper and middle back.\n\nThe traps consist of an upper (superior), middle, and lower (inferior) section, all of which contribute to neck mobility and elevating (lifting) and retracting (pulling back) the shoulder blade (scapula).\n\nDue to its role in posture and shoulder and neck movement, the trapezius muscle should be well-conditioned. Exercises like dumbbell shrugs and farmer's carries effectively target the traps."]);
musclesBackInfo.set("Shoulders", [Shoulders, partShoulders, "The shoulder includes the deltoid muscles (informally known as delts), which consist of 3 heads: anterior (front), lateral (middle), and posterior (rear). All 3 heads work together to enable arm movement.\n\nEach head specializes and exerts more force depending on the movement: the anterior head raises the arm forward, the lateral head raises the arm to the side, and the posterior head raises the arm backward.\n\nDue to the shoulder's importance in arm movement and mobility, it is vital to condition the deltoid muscles. Strength exercises that simulate a particular head's movement maximizes that head's muscle engagement (muscle isolation) but significantly reduces the engagement of the other heads.\n\nA popular exercise that effectively targets all 3 heads simultaneously is the shoulder press. Note that the more muscles involved in a movement, the less engaged a particular muscle is compared to a muscle isolation exercise (same idea as lifting a heavy object as a team vs lifting a heavy object by yourself)."]);
musclesBackInfo.set("Upper Arm", [UpperArm, partUpperArm, "The upper arm anchors the triceps, a three-headed muscle group that consists of the long, lateral, and medial head, all of which enable elbow extension (straightening of the arm).\n\nAny exercise that incorporates straightening of the arm from a bent position targets all 3 heads of the triceps - this includes push-downs, dumbbell kickbacks, push-ups, and swimming."]);
musclesBackInfo.set("Lats", [Lats, partLats, "The latissimus dorsi (or lats) is the largest muscle group in the upper body, spanning across the middle and lower back from the shoulder blades to the pelvis.\n\nThe lats are responsible for back stabilization and any movement related to pulling, such as driving the elbows back, bringing the arms toward the body (adduction), and shoulder blade adduction and depression.\n\nSports that heavily incorporate the engagement of the lats include swimming, climbing, and rowing. Other lat-based exercises include pull-ups, lat pull-downs, and barbell rows."]);
musclesBackInfo.set("Lower Back", [LowerBack, partLowerBack, "The lower back is composed of several muscles that protect and support the lumbar spine (the lower back region of the spine).\n\nBecause the lumbar spine supports the majority of the upper body's weight, the muscles that surround it are responsible for bearing that weight and the stress involved during lifting and bending backward (common when standing up).\n\nLower back pain is a condition common in older individuals, making it difficult to stand from a seated or bent position. Therefore, maintaining proper lower back health and strength is essential for better quality of life and resisting the effects of sarcopenia (muscle degradation), a phenomenon that naturally comes with age.\n\nA rather intense exercise that deeply engages the lower back is the deadlift. Bird dogs and glute bridges are more accessible options that improve pelvic stabilization and spinal alignment, both of which strengthen the lower back and ease lower back pain."]);
musclesBackInfo.set("Glutes", [Glutes, partGlutes, "The glutes comprise the main muscles of the buttocks. These muscles include the gluteus maximus, gluteus medius, and gluteus minimus.\n\nThe gluteus maximus is the largest and most superficial (closest to the surface of the skin) muscle of the 3 and is responsible for hip extension (moving leg backward at hip joint). The gluteus medius is the next underlying muscle and is responsible for hip abduction (moving leg away from body at hip joint). The gluteus minimus is the lowest muscle layer and is responsible for hip stabilization and abduction. Together, the glutes enable everyday movements such as walking, running, sitting, standing, and climbing stairs.\n\nThe squat is arguably the best exercise to strengthen the glutes - this compound exercise effectively targets all 3 muscles. Hip thrusts place more emphasis on the gluteus maximus, while lateral band walks place more emphasis on the gluteus medius and minimus. Walking and running are also great alternatives."]);
musclesBackInfo.set("Thigh", [Thigh, partThigh, "The thigh anchors the hamstring, a large muscle that spans the back of the thigh from the pelvis to the knee.\n\nThe hamstring is responsible for hip extension (moving leg backward at hip joint) and knee flexion (bending the knee). Therefore, it plays a major role in walking, running, sitting, standing, and climbing stairs.\n\nThe hamstrings can be worked by engaging in strength-based exercises like the squat and hamstring curl and cardio-based exercises like walking and running."]);
musclesBackInfo.set("Lower Leg", [LowerLeg, partLowerLeg, "The lower leg includes the calf muscle, a muscle group consisting of the gastrocnemius, soleus, and plantaris. Together, these muscles are responsible for plantarflexing (downward movement) the foot and toes.\n\nThe calf is engaged in everyday movements such as walking, running, jumping, and standing on the tips of the toes. Easily accessible exercises that effectively work the calves are walking, running, and calf raises."]);

export default musclesBackInfo;