import All from "./css/images/organs-body/organs.png"; import partGonads from "./css/images/organs-body/part-gonads.png"
import Brain from "./css/images/organs-body/organs-brain.png"; import partBrain from "./css/images/organs-body/part-brain.png";
import Esophagus from "./css/images/organs-body/organs-esophagus.png"; import partEsophagus from "./css/images/organs-body/part-esophagus.png";
import Lungs from "./css/images/organs-body/organs-lungs.png"; import partLungs from "./css/images/organs-body/part-lungs.png";
import Heart from "./css/images/organs-body/organs-heart.png"; import partHeart from "./css/images/organs-body/part-heart.png";
import Stomach from "./css/images/organs-body/organs-stomach.png"; import partStomach from "./css/images/organs-body/part-stomach.png";
import Liver from "./css/images/organs-body/organs-liver.png"; import partLiver from "./css/images/organs-body/part-liver.png";
import Gallbladder from "./css/images/organs-body/organs-gallbladder.png"; import partGallbladder from "./css/images/organs-body/part-gallbladder.png";
import Pancreas from "./css/images/organs-body/organs-pancreas.png"; import partPancreas from "./css/images/organs-body/part-pancreas.png";
import SI from "./css/images/organs-body/organs-SI.png"; import partSI from "./css/images/organs-body/part-SI.png";
import LI from "./css/images/organs-body/organs-LI.png"; import partLI from "./css/images/organs-body/part-LI.png";
import Kidneys from "./css/images/organs-body/organs-kidneys.png"; import partKidneys from "./css/images/organs-body/part-kidneys.png";
import Bladder from "./css/images/organs-body/organs-bladder.png"; import partBladder from "./css/images/organs-body/part-bladder.png";

/**
 * organsInfo map stores organ names, images, and descriptions for the BodyMap component
 * @author Earl Lontok
 */
const organsInfo = new Map();

organsInfo.set("All", [All, null, "Organs are specialized structures that perform a specific function or set of functions.\n\nThey are not found in all organisms - they are unique to multicellular ones. The cells of multicellular organisms (like humans) organize into tissues, and tissues organize and specialize into organs. Multiple organs often work together to form organ systems, which carry out complex functions essential to the proper development and survival of the organism.\n\nIn many cases, these functions involve maintaining homeostasis, an internal state in which physical and chemical conditions are dynamically kept in equilibrium. It is in this homeostatic state that the organism functions optimally."]);
organsInfo.set("Brain", [Brain, partBrain, "The brain is the most complex organ in the human body. All bodily functions are controlled by the brain, including, but not limited to, thought, memory, motor skills, and autonomic processes like breathing and heart rate.\n\nComposed of neurons and glial cells, the brain communicates with the body by sending and receiving electrical signals (nerve impulses) and chemical signals (neurotransmitters).\n\nThe brain is divided into 3 main components: brainstem, cerebellum, and cerebrum.\n\nThe brainstem connects the brain and the spinal cord and is responsible for autonomic processes like breathing, heart rate, blood pressure, and digestion. The cerebellum coordinates voluntary movement and balance. The cerebrum can be further divided into 4 lobes: frontal, temporal, parietal, and occipital.\n\nThe frontal lobe is responsible for personality, reasoning, and decision making. The temporal lobe is responsible for memory. The parietal lobe is responsible for sensory perception (sight, touch, hearing, smell, taste). The occipital lobe is responsible for vision."]);
organsInfo.set("Esophagus", [Esophagus, partEsophagus, "The esophagus is a long, hollow tube that allows the passage of food and liquid from the mouth to the stomach.\n\nLocated in front of the esophagus is the trachea, which is another tube that allows the passage of air between the mouth and the lungs.\n\nBecause both tubes have direct access to the mouth, a flap called the epiglottis opens/closes to determine passage, similar to a railroad track switch.\n\nWhile breathing, the epiglottis is open, allowing air to pass through the trachea.\n\nDuring ingestion, the act of swallowing pushes the epiglottis over the trachea, covering it and directing food and liquid to the esophagus. This protects the trachea from food/liquid, ultimately preventing choking/suffocation. If some food/liquid manages to enter the trachea, the body facilitates coughing to clear up the airway. Food then gets pushed down the esophagus toward the stomach via a series of wave-like contractions called peristalsis.\n\nSeparating the esophagus and the stomach is a muscular valve called the lower esophageal sphincter (or cardiac sphincter). This sphincter only opens to allow the passage of food and liquid to the stomach and immediately closes to prevent acid reflux (commonly known as heartburn)."]);
organsInfo.set("Lungs", [Lungs, partLungs, "The lungs are responsible for respiration (breathing).\n\nDuring inhalation, the lungs actively expand, allowing air to enter through the nose/mouth and pass through the trachea. The air then enters the lungs via bronchi, which divide into smaller tubes called bronchioles. At the end of each bronchiole is a tiny air sac (alveolus), which is surrounded by capillaries - this is where gas exchange takes place between the lungs and blood.\n\nOxygen, a molecule utilized by cells to produce energy (cellular respiration), diffuses from the lungs to the capillaries. Simultaneously, carbon dioxide, a waste product of cellular respiration, diffuses from the capillaries to the lungs.\n\nDuring exhalation, the lungs passively relax and shrink, releasing the carbon dioxide into the environment."]);
organsInfo.set("Heart", [Heart, partHeart, "The heart is the most hard-working muscle in the body, beating 60-100 times per minute at rest (40-60 for athletes), and it is responsible for circulating blood throughout the body.\n\nBlood is a special bodily fluid that absorbs oxygen from the lungs (respiration) and nutrients from the small intestine (digestion). Tissues throughout the body are supplied with said oxygen and nutrients via blood circulation facilitated by the heart.\n\nThe heart is divided into 2 sides (left and right) with 4 chambers total: left atrium and ventricle and right atrium and ventricle (a valve separates the atrium and ventricle to prevent backflow).\n\nFreshly oxygenated blood from the lungs enters the left atrium, gets pushed to the left ventricle, then pumped out to the body.\n\nAfter supplying the tissues with oxygen, the now deoxygenated blood enters the right atrium, gets pushed to the right ventricle, then pumped toward the lungs.\n\nThis rhythmic cycle repeats and dynamically adjusts its rate with respect to the body's oxygen and nutrient demand (ex: resting vs exercising)."]);
organsInfo.set("Stomach", [Stomach, partStomach, "The stomach is a sac-like organ where ingested food is stored and broken down.\n\nWhen food enters the stomach from the esophagus, a highly corrosive substance called hydrochloric acid (HCl) is secreted into the stomach.\n\nHCl breaks food down into a liquid substance called chyme (chyme eventually enters the small intestine). The acidity caused by HCl converts pepsinogen into pepsin, a digestive enzyme that breaks down proteins into smaller peptides and amino acids.\n\nIn addition to digestion, HCl also acts as protection. When swallowing, many unwanted bacteria and pathogens may join the food's/saliva's journey to the stomach. The highly acidic environment created by HCl is too harsh for most organisms, killing 99% of all microbes.\n\nHowever, the stomach is also at risk of corrosion. To combat this, the stomach is lined with mucus that is rich in bicarbonate (HCO3-). Bicarbonate is a base capable of neutralizing the hydrochloric acid."]);
organsInfo.set("Liver", [Liver, partLiver, "The liver is responsible for regulating chemical levels in the blood and producing bile.\n\nBile contains bile salts, a component that breaks down fats into smaller particles, making it easier for digestive enzymes to further break down the particles for absorption. While bile is produced in the liver, it is stored in the gallbladder, a small, pear-shaped organ located just below the liver.\n\nAll blood that leaves the stomach and intestines passes through the liver after which the liver filters out harmful substances (ex: toxins, drugs, alcohol) and metabolizes nutrients into usable forms of energy or storage (ex: excess glucose is converted into glycogen for storage).\n\nAny harmful substances broken down by the liver are excreted into the bile, which enters the intestines. Because these substances are classified by the body as bile by-products, they are not absorbed in the intestines and are ultimately excreted in the form of stool."]);
organsInfo.set("Gallbladder", [Gallbladder, partGallbladder, "The gallbladder is a small, pear-shaped organ located just below the liver. Bile produced by the liver is stored in the gallbladder.\n\nDuring digestion, the gallbladder secretes bile into the small intestine, specifically the duodenum, via a series of bile ducts called the biliary tract.\n\nBile contains bile salts, a component that breaks large fat globules into smaller particles, increasing its surface area and making it easier for digestive enzymes like lipase to further break down the particles for absorption."]);
organsInfo.set("Pancreas", [Pancreas, partPancreas, "The pancreas plays a key role in both digestion and blood glucose (blood sugar) regulation.\n\nDuring digestion, the pancreas secretes pancreatic juices containing enzymes into the small intestine, specifically the duodenum. These enzymes include amylase (breaks down carbohydrates), protease (breaks down proteins), and lipase (breaks down fats).\n\nDuring blood glucose regulation, the pancreas releases 2 antagonistic hormones: insulin (produced by beta cells) and glucagon (produced by alpha cells).\n\nWhen food is ingested, digested, and absorbed, blood glucose levels rise. This triggers the release of insulin, which binds to cells, opens receptors, and facilitates glucose intake into cells. Any excess glucose is converted into glycogen and stored in the liver, muscles, and adipose tissue (fat).\n\nWhen glucose is depleted, the release of glucagon is triggered, signaling the liver to convert stored glycogen back into glucose and release it into the bloodstream."]);
organsInfo.set("Small Intestine", [SI, partSI, "The small intestine is a long, tubular organ responsible for the further breakdown of food and the absorption of nutrients and water.\n\nIt is divided into three components from start to end: duodenum, jejunum, and ileum.\n\nChyme from the stomach enters the duodenum after which the small intestine secretes digestive enzymes. Bile from the gallbladder and other digestive enzymes from the pancreas are also secreted into the duodenum. The jejunum churns the mixture of food and digestive juices/enzymes via peristalsis. Nutrient absorption takes place in the ileum, the longest section of the small intestine.\n\nVilli and microvilli are small, finger-like projections that line the entirety of the inside of the small intestine. These projections increase surface area, which increases the rate of absorption of nutrients into the bloodstream."]);
organsInfo.set("Large Intestine", [LI, partLI, "The large intestine receives the remaining contents of the small intestine and excretes waste.\n\nWater and salt is further absorbed, which \"dehydrates\" the remaining contents, ultimately solidifying the waste into stool. The stool then makes its way to the rectum where it is stored until it is ready to be excreted via the anus.\n\nTo prevent stool from simply leaving the body, 2 circular valves stay closed: the internal and external anal sphincters.\n\nWhen stool enters the rectum, the rectum triggers the urge to defecate, involuntarily opening the internal anal sphincter. The external anal sphincter is voluntary, meaning it stays closed until the stool is forcibly excreted out to a toilet."]);
organsInfo.set("Kidneys", [Kidneys, partKidneys, "The kidneys are 2 bean-shaped organs that are responsible for filtering the blood and play a key role in the renal (or urinary) system.\n\nThe renal system follows 4 main processes: filtration, reabsorption, secretion, and excretion.\n\nThe nephron is the functional unit of the kidney (about 1 million per kidney), and each nephron consists of 2 components: the renal corpuscle and the renal tubule.\n\nThe renal corpuscle is where filtration takes place, specifically in the Bowman's capsule - blood from the glomerular capillaries is filtered by size into the Bowman's space via pressure (bulk flow). If the contents are small enough, they get filtered (ex: water, electrolytes, glucose, urea, etc.).\n\nThe renal tubule (a series of tubules and ducts) is where reabsorption and secretion take place. Essential contents that were filtered in the Bowman's capsule are forcibly reabsorbed by type from the tubules and into the blood. Waste and excess contents in the blood are forcibly secreted by type from the blood and into the tubules.\n\nAll contents that remain in the tubule exit toward the bladder via the ureter, ready to be excreted as urine."]);
organsInfo.set("Bladder", [Bladder, partBladder, "The bladder is a triangle-shaped, hollow organ that is responsible for storing urine. Urine from the kidneys enters the bladder via the ureter.\n\nThe bladder's walls are highly elastic, capable of storing up to 2 cups of urine for 2 to 5 hours. Its elasticity allows the walls to relax and passively expand as it fills with urine and contract and flatten to excrete the urine via the urethra."]);
organsInfo.set("Gonads", [All, partGonads, "Gonads are reproductive organs whose main function is to produce gametes and hormones necessary for sexual reproduction and the development of primary and secondary characteristics.\n\nMale gonads are the testicles, the reproductive organs responsible for producing sperm (male gametes) and hormones (testosterone).\n\nFemale gonads are the ovaries, the reproductive organs responsible for producing eggs (female gametes) and hormones (estrogen and progesterone).\n\nPrimary sex characteristics are present at birth (testes and penis in males and ovaries, uterus, and vagina in females), while secondary sex characteristics are physical traits that develop during puberty. Males develop muscles and body hair during puberty, while females develop breasts and wider hips."]);

export default organsInfo;