import All from "./css/images/organs-body/organs.png";
import Brain from "./css/images/organs-body/organs-brain.png";
import Esophagus from "./css/images/organs-body/organs-esophagus.png";
import Lungs from "./css/images/organs-body/organs-lungs.png";
import Heart from "./css/images/organs-body/organs-heart.png";
import Stomach from "./css/images/organs-body/organs-stomach.png";
import Liver from "./css/images/organs-body/organs-liver.png";
import Pancreas from "./css/images/organs-body/organs-pancreas.png";
import Gallbladder from "./css/images/organs-body/organs-gallbladder.png";
import SI from "./css/images/organs-body/organs-SI.png";
import LI from "./css/images/organs-body/organs-LI.png";
import Kidneys from "./css/images/organs-body/organs-kidneys.png";
import Bladder from "./css/images/organs-body/organs-bladder.png";

const organsInfo = new Map();
organsInfo.set("All", All);
organsInfo.set("Brain", Brain);
organsInfo.set("Esophagus", Esophagus);
organsInfo.set("Lungs", Lungs);
organsInfo.set("Heart", Heart);
organsInfo.set("Stomach", Stomach);
organsInfo.set("Liver", Liver);
organsInfo.set("Pancreas", Pancreas);
organsInfo.set("Gallbladder", Gallbladder);
organsInfo.set("Small Intestine", SI);
organsInfo.set("Large Intestine", LI);
organsInfo.set("Kidneys", Kidneys);
organsInfo.set("Bladder", Bladder);

export default organsInfo;