import All from "./css/images/skeleton-body/skeleton.png";
import Head from "./css/images/skeleton-body/skeleton-head.png"; import partHead from "./css/images/skeleton-body/part-head.png";
import Collar from "./css/images/skeleton-body/skeleton-collar.png"; import partCollar from "./css/images/skeleton-body/part-collar.png";
import UpperArm from "./css/images/skeleton-body/skeleton-upper-arm.png"; import partUpperArm from "./css/images/skeleton-body/part-upper-arm.png";
import Forearm from "./css/images/skeleton-body/skeleton-forearm.png"; import partForearm from "./css/images/skeleton-body/part-forearm.png";
import Hands from "./css/images/skeleton-body/skeleton-hands.png"; import partHands from "./css/images/skeleton-body/part-hands.png";
import Spine from "./css/images/skeleton-body/skeleton-spine.png"; import partSpine from "./css/images/skeleton-body/part-spine.png";
import Torso from "./css/images/skeleton-body/skeleton-torso.png"; import partTorso from "./css/images/skeleton-body/part-torso.png";
import Hip from "./css/images/skeleton-body/skeleton-hip.png"; import partHip from "./css/images/skeleton-body/part-hip.png";
import Thigh from "./css/images/skeleton-body/skeleton-thigh.png"; import partThigh from "./css/images/skeleton-body/part-thigh.png";
import LowerLeg from "./css/images/skeleton-body/skeleton-lower-leg.png"; import partLowerLeg from "./css/images/skeleton-body/part-lower-leg.png";
import Feet from "./css/images/skeleton-body/skeleton-feet.png"; import partFeet from "./css/images/skeleton-body/part-feet.png";

/**
 * skeletonInfo map stores skeleton names, images, and descriptions for the BodyMap component
 * @author Earl Lontok
 */
const skeletonInfo = new Map();

skeletonInfo.set("All", [All, null, "The skeleton is the body's support structure. Composed of bones, cartilage, ligaments, and tendons, the skeleton has 2 main functions: giving the body its shape and protection.\n\nThe skeleton supports the weight of the body and serves as the anchor for all tissue that connects to it. It also acts as armor (the ribs in particular), protecting vital organs.\n\nBones are rigid tissues composed of cells, proteins (ex: collagen), and minerals (ex: calcium). Cartilage is a flexible connective tissue located at joints, acting as a shock absorber and preventing friction between bones. Ligaments connect bones to bones, while tendons connect muscles to bones."]);
skeletonInfo.set("Head", [Head, partHead, "The skull (medical name: cranium) is a set of bones responsible for protecting the brain (and other sensory organs like the eyes, nose, mouth, and ears) and anchoring facial tissues.\n\nThe skull is divided into 2 main components: cranial bones (or neurocranium) and facial bones (or viscerocranium). The neurocranium includes the bones that house and protect the brain, while the viscerocranium includes the bones that support facial muscles."]);
skeletonInfo.set("Collar", [Collar, partCollar, "The collarbone (medical term: clavicle) is a long, slender bone that connects the sternum and the shoulder blade and is responsible for the stabilization and flexibility of the shoulder.\n\nDue to its thin structure and small area of connectivity, the clavicle is highly prone to injury like clavicle fracture and shoulder dislocation. Contact sports and falls are the most common causes of clavicle-related injuries."]);
skeletonInfo.set("Upper Arm", [UpperArm, partUpperArm, "The upper arm bone (medical term: humerus) runs from the shoulder to the elbow. Being the longest bone in the upper body, it anchors powerful muscles like the biceps and triceps."]);
skeletonInfo.set("Forearm", [Forearm, partForearm, "The forearm consists of 2 bones: the ulna and the radius.\n\nThe ulna is the longer, thinner bone situated on the pinky side, while the radius is the shorter, thicker bone situated on the thumb side. Both bones run from the elbow to the hand, providing structure, support, and wrist movement."]);
skeletonInfo.set("Hands", [Hands, partHands, "The hand is divided into 3 sets of bones: phalanges, metacarpals, and carpals.\n\nThe phalanges consist of 3 bones on each digit (distal, middle, and proximal from tip to base) with the exception of the thumb (only has distal and proximal), totaling 14 bones. The metacarpals consist of 5 bones that comprise the palm of the hand. The carpals consist of 8 bones that comprise the wrist."]);
skeletonInfo.set("Spine", [Spine, partSpine, "The spine (or backbone) is a long column of bones that runs from the base of the skull to the tailbone. It is responsible for housing and protecting the spinal cord, a long bundle of nerves that serves as a vital communication pathway between the brain and the rest of the body.\n\nSerious damage to the spine (specifically, the spinal cord) can lead to neurological conditions like paralysis, the partial or complete loss of muscle function.\n\nThe spine consists of several stacked bones called vertebrae. Between them is an intervertebral disk, a soft, round cushion that acts as a shock absorber. A facet joint and cartilage also sit between vertebrae, enabling spinal flexibility and stability."]);
skeletonInfo.set("Torso", [Torso, partTorso, "The rib cage (medical term: thoracic cage) is a cage-like structure that surrounds and protects vital organs located in the thoracic cavity and serves as an anchor for core muscles like the abs, obliques, and the diaphragm.\n\nConsisting of 24 bones (12 on each side), the ribs wrap around the side from the sternum (breastbone) to the thoracic vertebrae (the thoracic section of the spine)."]);
skeletonInfo.set("Hip", [Hip, partHip, "The hips contain the pelvis, a bony structure that connects the upper body and the lower body (specifically, connects the spine and the legs).\n\nThe pelvis houses and protects the urinary and reproductive organs (located in the pelvic cavity) in addition to stabilizing and supporting the weight of the upper body."]);
skeletonInfo.set("Thigh", [Thigh, partThigh, "The thighbone (medical term: femur) is the longest (and strongest) bone in the body.\n\nSpanning from the pelvis to the knee, the femur serves as the anchor for several ligaments, tendons, and powerful muscles that enable standing, movement, and balance. It is highly durable, capable of withstanding stress and trauma."]);
skeletonInfo.set("Lower Leg", [LowerLeg, partLowerLeg, "The lower leg consists of 2 bones: the tibia and the fibula.\n\nThe tibia is the longer, stronger bone that runs along the shin from the knee to the ankle, while the fibula is the shorter, weaker bone that runs along the calf. Due to its strength, the tibia is weight-bearing - the fibula does not bear as much weight and primarily serves as structural support."]);
skeletonInfo.set("Feet", [Feet, partFeet, "The foot is divided into 3 sets of bones: phalanges, metatarsals, and tarsals.\n\nThe phalanges consist of 3 bones on each digit (distal, middle, and proximal from tip to base) with the exception of the thumb toe (only has distal and proximal), totaling 14 bones. The metatarsals consist of 5 long bones that span the forefoot and connect to the base of the phalanges. The tarsals consist of 7 bones that comprise the midfoot, hindfoot, and part of the lower ankle."]);

export default skeletonInfo;